[project]
name = "generic-cache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools",
    "fastapi",
    "gunicorn",
    "uvicorn",
    "httpx",
    "requests",
    "redis",
]
